export interface Questions {
    id: number;
    questionText: string;
    options: string[];
    answer: string;
    category: string;
}

export const questions: Questions[] = [
 
    {
        id: 1,
        questionText: "What is the chemical symbol for water?",
        options: ["H2O", "CO2", "O2", "NaCl"],
        answer: "H2O",
        category: "General Science",
    },
    {
        id: 2,
        questionText: "What planet is known as the Red Planet?",
        options: ["Earth", "Mars", "Venus", "Jupiter"],
        answer: "Mars",
        category: "General Science",
    },
    {
        id: 3,
        questionText: "What gas do plants primarily use for photosynthesis?",
        options: ["Oxygen", "Carbon Dioxide", "Nitrogen", "Methane"],
        answer: "Carbon Dioxide",
        category: "General Science",
    },
    {
        id: 4,
        questionText: "What is the hardest natural substance on Earth?",
        options: ["Gold", "Iron", "Diamond", "Platinum"],
        answer: "Diamond",
        category: "General Science",
    },
    {
        id: 5,
        questionText: "What is the powerhouse of the cell?",
        options: ["Nucleus", "Ribosome", "Mitochondria", "Chloroplast"],
        answer: "Mitochondria",
        category: "General Science",
    },
    {
        id: 6,
        questionText: "What is the boiling point of water at sea level?",
        options: ["90°C", "100°C", "120°C", "150°C"],
        answer: "100°C",
        category: "General Science",
    },
    {
        id: 7,
        questionText: "What is the largest organ in the human body?",
        options: ["Heart", "Liver", "Skin", "Lungs"],
        answer: "Skin",
        category: "General Science",
    },
    {
        id: 8,
        questionText: "What is the study of earthquakes called?",
        options: ["Meteorology", "Seismology", "Geology", "Volcanology"],
        answer: "Seismology",
        category: "General Science",
    },
    {
        id: 9,
        questionText: "What is the chemical symbol for sodium?",
        options: ["S", "Na", "So", "N"],
        answer: "Na",
        category: "General Science",
    },
    {
        id: 10,
        questionText: "What element does the symbol 'O' represent on the periodic table?",
        options: ["Oxygen", "Osmium", "Oganesson", "Gold"],
        answer: "Oxygen",
        category: "General Science",
    },
    {
        id: 11,
        questionText: "Who is the current Secretary-General of the United Nations?",
        options: ["Ban Ki-moon", "Kofi Annan", "Antonio Guterres", "Boutros Boutros-Ghali"],
        answer: "Antonio Guterres",
        category: "Current Affairs",
    },
    {
        id: 12,
        questionText: "Which country hosted the 2024 Summer Olympics?",
        options: ["Tokyo", "Paris", "Los Angeles", "Beijing"],
        answer: "Paris",
        category: "Current Affairs",
    },
    {
        id: 13,
        questionText: "Who is the current President of the United States?",
        options: ["Joe Biden", "Donald Trump", "Barack Obama", "Kamala Harris"],
        answer: "Joe Biden",
        category: "Current Affairs",
    },
    {
        id: 14,
        questionText: "What is the name of India's current Prime Minister?",
        options: ["Narendra Modi", "Rahul Gandhi", "Amit Shah", "Manmohan Singh"],
        answer: "Narendra Modi",
        category: "Current Affairs",
    },
    {
        id: 15,
        questionText: "Which country recently exited the European Union?",
        options: ["France", "Germany", "United Kingdom", "Italy"],
        answer: "United Kingdom",
        category: "Current Affairs",
    },
    {
        id: 16,
        questionText: "Which company became the first to reach a $3 trillion valuation?",
        options: ["Apple", "Google", "Microsoft", "Amazon"],
        answer: "Apple",
        category: "Current Affairs",
    },
    {
        id: 17,
        questionText: "Who won the 2023 FIFA Women's World Cup?",
        options: ["USA", "England", "Spain", "Germany"],
        answer: "Spain",
        category: "Current Affairs",
    },
    {
        id: 18,
        questionText: "Which country recently landed a rover on the moon's south pole?",
        options: ["China", "Russia", "India", "USA"],
        answer: "India",
        category: "Current Affairs",
    },
    {
        id: 19,
        questionText: "What is the name of the world's largest active volcano that erupted in 2022?",
        options: ["Mount St. Helens", "Mauna Loa", "Mount Etna", "Krakatoa"],
        answer: "Mauna Loa",
        category: "Current Affairs",
    },
    {
        id: 20,
        questionText: "Which global organization declared 2024 as the International Year of Camelids?",
        options: ["UNESCO", "FAO", "WHO", "UNICEF"],
        answer: "FAO",
        category: "Current Affairs",
    },
    {
        id: 21,
        questionText: "Who was the first President of the United States?",
        options: ["Abraham Lincoln", "George Washington", "Thomas Jefferson", "John Adams"],
        answer: "George Washington",
        category: "History",
    },
    {
        id: 22,
        questionText: "In which year did World War II end?",
        options: ["1939", "1945", "1950", "1965"],
        answer: "1945",
        category: "History",
    },
    {
        id: 23,
        questionText: "Who was known as the Iron Lady?",
        options: ["Margaret Thatcher", "Indira Gandhi", "Golda Meir", "Angela Merkel"],
        answer: "Margaret Thatcher",
        category: "History",
    },
    {
        id: 24,
        questionText: "What ancient civilization built the pyramids?",
        options: ["Romans", "Greeks", "Egyptians", "Mayans"],
        answer: "Egyptians",
        category: "History",
    },
    {
        id: 25,
        questionText: "Who discovered America in 1492?",
        options: ["Christopher Columbus", "Marco Polo", "Vasco da Gama", "Ferdinand Magellan"],
        answer: "Christopher Columbus",
        category: "History",
    },
    {
        id: 26,
        questionText: "Which empire was ruled by Genghis Khan?",
        options: ["Roman Empire", "Mongol Empire", "Ottoman Empire", "Persian Empire"],
        answer: "Mongol Empire",
        category: "History",
    },
    {
        id: 27,
        questionText: "What was the name of the ship on which the Pilgrims traveled to America?",
        options: ["Titanic", "Mayflower", "Santa Maria", "Endeavour"],
        answer: "Mayflower",
        category: "History",
    },
    {
        id: 28,
        questionText: "Who was the first female ruler of ancient Egypt?",
        options: ["Cleopatra", "Hatshepsut", "Nefertiti", "Ankhesenamun"],
        answer: "Hatshepsut",
        category: "History",
    },
    {
        id: 29,
        questionText: "Which treaty ended World War I?",
        options: ["Treaty of Paris", "Treaty of Versailles", "Treaty of Ghent", "Treaty of Vienna"],
        answer: "Treaty of Versailles",
        category: "History",
    },
    {
        id: 30,
        questionText: "Which Indian leader was known as the 'Father of the Nation'?",
        options: ["Jawaharlal Nehru", "Subhash Chandra Bose", "Mahatma Gandhi", "Bhagat Singh"],
        answer: "Mahatma Gandhi",
        category: "History",
    },
 
]